server {
    listen 81;
    server_name wordpress;

    access_log /var/log/angie/wordpress.access_log extended;

    gzip on;

    location / {
        proxy_pass http://158.160.30.99:8080;
        proxy_set_header Accept-Encoding '';
        sub_filter '58.160.30.99:8080' '58.160.30.99:81';
        sub_filter_once off;
        proxy_redirect '58.160.30.99:8080' '58.160.30.99:81';
        proxy_hide_header Link;
    }

    location ~* \.(css|js|woff2)$ {
        root /var/www/html;
    }
}