#Определение переменной с помощью map;
map $request_uri $images_new {
    default "images";
}

# Игнорировать пустые поля server_name
server {
    listen 80;
    server_name "";

    return 444;
}

# Отправлять 444 если нет поля server_name
server {
    listen 80;
    server_name _;

    return 444;
}

server {
    listen 80;
    server_name test;

    #return 200 "server test!!!!!!!!";

    location / {
        root /usr/share/angie/test/static-site;
        index index.html index.htm;
        #return 200 "location / test!!!!!!!!";
    }

    # Диреткория /images с регулярным выражением
    location ~*\.(gif|jpg|jpeg|png|gif)$ {
        root /usr/share/angie/test/static-site/images;
        #return 200 "location images test!!!!!!!!";
    }
    # Директория /images
    location /$images_new/ {
    autoindex on;
    }

    # Директория /error с внутренним перенаправлением
    location /error/ {
        index index.html;
        internal;
    }

    # Ошибки 5xx
    error_page  500 502 503 504 /50x.html;
    location = /50x.html {
        root   error/index.html;
    }

    # Ошибки 404 внутри
    error_page 404 /error/index.html;
    location = /error/index.html {
        internal;
    }

    # Перенаправление
    location /old {
        rewrite ^/old / redirect;
    }

}