upstream u1 {
    zone u1 1m;
    hash $scheme$request_uri consistent;
    server 127.0.0.1:9000;
    server 127.0.0.1:9001;
    server 127.0.0.1:9002;
    server 127.0.0.1:9003;
}
resolver 127.0.0.53 status_zone=resolver;
server {
    listen 82;
    status_zone balance;
    index index.html index.htm;
    server_name _;
    location / {
        status_zone location_root;
        proxy_pass http://u1;
    }
}