server {
    listen 81 default_server reuseport;
    server_name wordpress;

    access_log /var/log/angie/wordpress.access_log extended;

    gzip on;

    location / {
        proxy_pass http://158.160.6.91:8080;
        proxy_set_header Accept-Encoding '';
        sub_filter '158.160.6.91:8080' '158.160.6.91:81';
        sub_filter_once off;
        proxy_redirect '158.160.6.91:8080' '158.160.6.91:81';
        proxy_hide_header Link;
        reset_timedout_connection on;
        proxy_connect_timeout 5;
        proxy_send_timeout 10;
        proxy_read_timeout 10;
        proxy_temp_file_write_size 64k;
        proxy_buffer_size 4k;
        proxy_buffers 64 4k;
        proxy_busy_buffers_size 32k;
        proxy_cache one;
        proxy_cache_valid 200 1h;
        proxy_cache_lock on;
        proxy_cache_min_uses 2;
        proxy_ignore_headers "Cache-Control" "Expires";
        proxy_cache_use_stale updating error timeout invalid_header http_500 http_502 http_504;
        proxy_cache_background_update on;
    }

    location ~* \.(css|js|woff2)$ {
        root /var/www/html;
    }
}